#!/bin/bash
pid="$(ps -ef | grep shopclock | awk '/python/ {print $2}')"
if [ -n "$pid" ]; then
  echo "Found running shopclock at PID $pid...killing"
  kill $pid
fi
export DISPLAY=:0
./shopclock.py &
pid="$(ps -ef | grep shopclock | awk '/python/ {print $2}')"
echo "shopclock running at PID $pid"

