# time and date format - see https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior
timeFormat: "%I:%M:%S %p"
dateFormat: "%A %B %d %Y"

backgroundColor: "#222255"
timeDateColor: "yellow"
timeDateBackgroundColor: "black"
timeDateFont: "Sans Bold"

screenWidth: 800
screenHeight: 480
topBandHeight: 30
bottomBandHeight: 0
tileSizeSmall: 175
tileSizeLarge: 450
defaultIconSize: 175
animationSteps: 24

tileRefreshTime: 15 # seconds

tiles:
-
  type: WeatherCurrent
  textColor: "#000060"
  backgroundColor: "#CCCCFF"
-
  type: WeatherForecast
  textColor: "white"
  backgroundColor: "black"
-
  type: CPUTemperature
  textColor: blue
  backgroundColor: white
#-
#  type: Text
#  text: "BLUE"
#  textColor: white
#  backgroundColor: "#000080"

# see https://openweathermap.org/appid to obtain an API key
openWeatherAPIKey: "12345123451234512345123451234512"
# see http://bulk.openweathermap.org/sample/city.list.json.gz to obtain your city ID
openWeatherCityID: "5128638" # New York, NY, USA
openWeatherUpdateInterval: 600 # seconds

